### ISSUE TITLE
[FEATURE] Xoá thanh máu

### ISSUE THREAD

**Issue by BrianfromRageVN** [RAGEVN/issues#12]
**Giới thiệu**
Xoá thanh máu

**Chi tiết**
Nên xoá thanh máu, nhìn không đẹp

**Thông tin thêm**
![image](https://user-images.githubusercontent.com/101466788/158386391-bb811e8c-4bd1-4196-90e8-185d710b5f8a.png)

**Comment by duydang2311** [comment]
Xóa hay làm nó đẹp hơn?

**Comment by duydang2311** [comment]
Will do.

**Comment by BrianfromRageVN** [comment]
Thay vào đó làm 1 lệnh /setinjuries : Mieu ta vet thuong /setinjuries [mô tả vết thương] 
Người khác sẽ dùng lệnh /checkinjuries [ID] nó sẽ show đó ra.

**Comment by duydang2311** [comment]
> Thay vào đó làm 1 lệnh /setinjuries : Mieu ta vet thuong /setinjuries [mô tả vết thương] Người khác sẽ dùng lệnh /checkinjuries [ID] nó sẽ show đó ra.

Create a separate feature request issue for it.

**Comment by duydang2311** [comment]
Completely removed the default nametag. Will implement RAGE:VN's own nametag.
